### ISSUE TITLE
hi，

### ISSUE THREAD

**Issue by leejshades** [htwenhe/vfOA#4]
![qq 20180625140509](https://user-images.githubusercontent.com/7189444/41832913-ca916bdc-7880-11e8-882d-84c254bd051f.png)
请问您，这个怎么解决呢？麻烦您看一下

**Comment by htwenhe** [comment]
python2.7能不能跑不记得了。建议你升级一下版本，我用的3.6的版本。

这个问题你在终端下运行“pip install dj_database_url” 试一下。
________________________________
发件人: hadeslee <notifications@github.com>
发送时间: 2018年6月25日 14:05
收件人: htwenhe/vfOA
抄送: Subscribed
主题: [htwenhe/vfOA] hi， (#4)


[qq 20180625140509]<https://user-images.githubusercontent.com/7189444/41832913-ca916bdc-7880-11e8-882d-84c254bd051f.png>
请问您，这个怎么解决呢？麻烦您看一下

―
